# Form implementation generated from reading ui file 'posApp.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle("POS Application - F1D022075 - Muhammad Nune Huria Sakti")
        MainWindow.resize(802, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 60, 491, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # Identity
        self.identity_group = self.create_identity_group()
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.addWidget(self.identity_group)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        # Product
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.label = QtWidgets.QLabel("Product \t:", parent=self.verticalLayoutWidget)
        self.horizontalLayout.addWidget(self.label)
        
        self.comboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.products = {
            ""
            "Bimoli (Rp 20.000)": 20000,
            "Beras 5 Kg (Rp 75.000)": 75000,
            "Kecap XYZ (Rp 7.000)": 7000,
            "Saos Tiram (Rp 10.000)": 10000
        }
        self.comboBox.addItems(self.products.keys())
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        
        # Quantity
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.label_3 = QtWidgets.QLabel("Quantity\t:", parent=self.verticalLayoutWidget)
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(1000)
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        
        # Discount
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.label_2 = QtWidgets.QLabel("Discount\t:", parent=self.verticalLayoutWidget)
        self.horizontalLayout_2.addWidget(self.label_2)
        
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.discounts = {"0%": 0, "5%": 5, "10%": 10, "15%": 15}
        self.comboBox_2.addItems(self.discounts.keys())
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        
        # Buttons
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.pushButton = QtWidgets.QPushButton("Add to cart", parent=self.verticalLayoutWidget)
        self.pushButton.clicked.connect(self.add_to_cart)
        self.horizontalLayout_4.addWidget(self.pushButton)
        
        self.pushButton_2 = QtWidgets.QPushButton("Clear", parent=self.verticalLayoutWidget)
        self.pushButton_2.clicked.connect(self.clear_cart)
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        
        # Cart List
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.listWidget = QtWidgets.QListWidget(parent=self.verticalLayoutWidget)
        self.verticalLayout_3.addWidget(self.listWidget)
        
        self.label_4 = QtWidgets.QLabel("Total: Rp 0", parent=self.verticalLayoutWidget)
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)

        MainWindow.setCentralWidget(self.centralwidget)
        
    def add_to_cart(self):
        product = self.comboBox.currentText()
        price = self.products[product]
        quantity = self.spinBox.value()
        discount = self.discounts[self.comboBox_2.currentText()]
        
        subtotal = price * quantity
        discount_amount = subtotal * (discount / 100)
        final_price = subtotal - discount_amount
        
        self.listWidget.addItem(f"{product} x {quantity} - Rp {final_price:,.0f} (Discount: {discount}%)")
        self.update_total()
    
    def update_total(self):
        total = 0
        for index in range(self.listWidget.count()):
            text = self.listWidget.item(index).text()
            price_part = text.split('- Rp ')[1].split(' ')[0] 
            total += int(price_part.replace(',', '')) 

        self.label_4.setText(f"Total: Rp {total:,.0f}")

    
    def clear_cart(self):
        self.listWidget.clear()
        self.label_4.setText("Total: Rp 0")

    def create_identity_group(self):
        identity_group = QtWidgets.QGroupBox("Identity")

        layout = QtWidgets.QVBoxLayout()
        layout.addWidget(QtWidgets.QLabel("Nama\t: Muhammad Nune Huria Sakti"))
        layout.addWidget(QtWidgets.QLabel("NIM\t: F1D022075"))
        layout.addWidget(QtWidgets.QLabel("Kelas\t: Pemrograman Visual - C"))

        identity_group.setLayout(layout)
        return identity_group
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
